config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get  '/register',        to: 'users#new'
  get  '/login',           to: 'sessions#new'
  post '/login',           to: 'sessions#create'
  get  '/logout',          to: 'sessions#destroy'
  get  '/forgot_password', to: 'sessions#forgot_password'
  post '/forgot_password', to: 'sessions#reset_password'
  get  '/pin',              to: 'sessions#pin'
  post '/pin',             to: 'sessions#pin'

  match '/auth/:provider/callback' => 'sessions#create_omniauth', via: :get

  resources :users, except: [:destroy] do
    resources :posts
    resources :comments, only: [:create, :show]
  end

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
    member do
      post :vote
    end
  end

  resources :categories, except: [:edit, :update, :destroy] do
    resources :posts
  end

  resources :comments, only: [:vote] do
    member do
      post :vote
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include VoteableGemille

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
  validates :user_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was added."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class='span0 well text-center'>
  <% if logged_in? && comment.valid? %>
    <%= link_to vote_comment_path(comment, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br/>
   <span id='comment_<%= comment.id %>_votes'><%= comment.total_votes %> Votes</span>
    <br/>
    <%= link_to vote_comment_path(comment, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  <% else %>
    <%= comment.total_votes %> Votes
  <% end %>
</div>

<div class="row">
  <div class='span8 well'>
    <p><em><%= simple_format h comment.body %></em></p>
    <%= render 'shared/creation_stats', post_type: comment %>
    <% if show_post %>
      <span class='quiet'>original post: <%= link_to comment.post.title, post_path(comment.post) %></span>
    <% end %>
    </div>
  </div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%= @comment.id %>_votes').html('<%= @comment.total_votes %> Votes');
<% else %>
  alert('You can only vote on a comment once.');
<% end %>