config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get  '/register',        to: 'users#new'
  get  '/login',           to: 'sessions#new'
  post '/login',           to: 'sessions#create'
  get  '/logout',          to: 'sessions#destroy'
  get  '/forgot_password', to: 'sessions#forgot_password'
  post '/forgot_password', to: 'sessions#reset_password'
  get  '/pin',              to: 'sessions#pin'
  post '/pin',             to: 'sessions#pin'

  match '/auth/:provider/callback' => 'sessions#create_omniauth', via: :get

  resources :users, except: [:destroy] do
    resources :posts
    resources :comments, only: [:create, :show]
  end

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
    member do
      post :vote
    end
  end

  resources :categories, except: [:edit, :update, :destroy] do
    resources :posts
  end

  resources :comments, only: [:vote] do
    member do
      post :vote
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base

  include VoteableGemille
  include SluggableGemille

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 3}
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]

  def index
    @posts = Post.all.sort_by {|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post was updated."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def vote
    @vote =  Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end
end

app/views/posts/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %>
</span>

app/views/posts/_creation_stats.html.erb
<span class='quiet'>
  posted by <%=link_to post_type.creator.username, user_path(post_type.creator.id) %>
  <small>on <%= time_of_post(post_type.created_at) %></small><br>
</span>

app/views/posts/_form.html.erb
<div class='well'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <br>
      <%= f.label :url %>
      <%= f.text_field :url %>
      <br>
      <br>
    </div>
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description %>
      <br>
      <% user_id = current_user.id %>
      <br>
      <br>
      <div class='form-inline', 'control-group'>
        <%= f.label :categories %>
        <br>
        <%= f.collection_check_boxes:category_ids, Category.all, :id, :name, {:item_wrapper_class => 'inline'} %>
      </div>
      <br>
      <%= f.submit(@post.new_record? ? "Create Post" : "Update Post", class: 'btn btn-primary') %>
  <% end %>
    </div>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_path(post.id, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
     <span id='post_<%= post.id %>_votes'><%= post.total_votes %> Votes</span>
      <br/>
      <%= link_to vote_post_path(post.id, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% else %>
      <%= post.total_votes %> Votes
    <% end %>
  </div>

  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= simple_format h post.description %> </p>
    <p>
      <%= render 'shared/creation_stats', post_type: post %>
      <p>
        <%= link_to ("#{post.comments.size} comments"), post_path(post) %>
      </p>
      </span>
      </p>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit this Post" %>

<%= render 'shared/error', form: @post %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>


<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>

<%= render 'shared/error', form: @post %>
<%= render 'form' %>

app/views/posts/show.html.erb
<p>
  <%= render @post.categories %>
</p>

<%= link_to @post.title, fix_url(@post.url) %>
<br>
<p>
  <%= simple_format h @post.description %>
</p>
<hr/>

<%= render 'shared/creation_stats', post_type: @post %>

<p class>
  <% if (session[:user_id] == @post.creator.id) || (logged_in? && current_user.admin?) %>
  [<%= link_to 'edit this Post', edit_post_path(@post) %>]
  <% end %>
</p>
<br>

<%= render 'shared/error', form: @comment %>

<% if current_user.nil? %>
<p>
<% @post.comments.each do |comment| %>
  <div class="row">
    <div class='span8 well'>
      <p><em><%= simple_format h comment.body %></em></p>
      <p>
        <%= render 'shared/creation_stats', post_type: comment %>
    </div>
  </div>
<% end %>
</p>
<% else %>
<h5>Create a comment:</h5>
<%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Create comment", class: 'btn btn-primary' %>
<% end %>

<p>
<% @post.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>
</p>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.id %>_votes').html('<%= @post.total_votes %> Votes')
<% else %>
  alert('You can only vote on a post once.');
<% end %>